### ISSUE TITLE
Proper derivation of source and destination service attributes

### ISSUE THREAD

**Issue by kyessenov** [istio/old_pilot_repo#1315]
As observed in https://github.com/istio/pilot/pull/1307, `destination.service` is being set to `b.namespace.svc.cluster.local,headless.namespace.svc.cluster.local` which doesn't work with any of the mixer configs. Additionally, neither `destination.name` nor `destination.namespace` is being set either. We need to pick one service out of the list, and also set `name` and `namespace` to avoid re-derivation of those values.

cc @smawson @mandarjog @costinm @rshriram

**Comment by douglas-reid** [comment]
It might be kinda lame, but is one option to simply document that this multi-service scenario is not yet supported?

**Comment by kyessenov** [comment]
It certainly is an option. That needs to be made clear in the docs as I saw user reports of the similar type of an error. How do we minimize the surprise factor here? If pilot does not set `destination.name`, I assume Mixer recomputes it, but not from `destination.service`, right?

**Comment by andraxylia** [comment]
How big is the fix and how much collateral can it cause?

**Comment by mandarjog** [comment]
In a multi service scenario the mode of failure cannot be controlled easily. The list will be sorted alphabetically, so if you happen to have an additional service, things will fail in a difficult to control way.

We start from clusterIP at the source, so we precisely know the destination. This needs to  be propagated to the destination.

From what I have seen `destination.name` is also not being set correctly. It should be the short name of the service, not the hostname of the pod. 
We need to fix the attribute vocabulary as well. At present `destination.service` and `destination.name` are defined to be the same.
https://istio.io/v-0.1/docs/reference/config/mixer/attribute-vocabulary.html

`destination.service` (fully qualified, host header)
`destination.name` (shortname of the service)   (equivalent to the app label)
`destination.namespace` 

`destination.name` gives the best UX while writing rules, because destination.namespace is already implicitly matched.

**Comment by rshriram** [comment]
My two cents: we can leave the behavior as is and tell people that we do not handle the one pod in multiple services scenario. Its unnecessary complexity to add code everywhere to do do guess work.

**Comment by douglas-reid** [comment]
@kyessenov and @mandarjog right now, Mixer does not compute `destination.name` (or `source.name`). we could alter that behavior fairly easily if it were desirable.

**Comment by kyessenov** [comment]
@rshriram the problem is this guess work is already present, but pilot and mixer guess different things. That will lead to strange behaviors.

**Comment by andraxylia** [comment]
Can somebody write in the description a nice detailed explanation of what is a "multi-service scenario", along with the use cases and examples @ZackButcher can you help here please?

**Comment by ZackButcher** [comment]
In k8s we can wind up in a multi-service scenario relatively easily: services just select a group of pods by label. A simple example would be renaming an existing service, where I define a second, different service name that points at the same set of pods, but I leave the old one around to ease transition for my callers.

A second use-case is very common inside of Google: I host multiple APIs on the same binary (gRPC server, using a single port) but refer to them by separate names. The canonical example is the Operations service: the binary's "primary" service returns a long running operation, and implements the Operation service to allow the user to poll the long running operation's progress. (Here's an example, where [CreateProject returns a LRO](https://cloud.google.com/resource-manager/reference/rest/v1/projects/create), and the same service implements the [Operations API to allow polling](https://cloud.google.com/resource-manager/reference/rest/v1/operations)). While both services are hosted on the same public name (`cloudresourcemanager.googleapis.com/v1/...`), under the hood they have separate service names to allow them to be managed separately. But both service names map to the same binary/pod.

In the same vein as above, imagine a company moving from a monolith to a microservices architecture. A first step might be to containerize the monolith and deploy it in k8s, gradually moving functionality into new binaries. In that case I want to define separate k8s services for each API I intend to move out of the monolith. Then my clients can use the name of the k8s service for the API they need to access, and as I move that API's implementation out of the monolith it's transparent to my callers that they're being routed to a new binary: they didn't need to change the name of the service they're calling.

Health checking can also be thought of as multiple services on the same pod.

**Comment by andraxylia** [comment]
Given all the above, I agree we cannot fix this in upcoming release next week, but we should document the limitation and fix it with high priority right after. Since we will switch to a faster release cycle, the fix will be released soon.

**Comment by kyessenov** [comment]
Thank you for examples @ZackButcher . I think there's a lot of power and flexibility in separating the service names (addresses by which clients call servers) from the service workloads (physical servers or pods). I don't see why this particular issue should force us to create a one-to-one correspondence between the two. There's a relatively simple fix to pass `destination` address from the client, that would fully address this issue for HTTP traffic.

**Comment by smawson** [comment]
A couple quick notes:
- For HTTP, client is already passing destination service in the Host header, no need to send it elsewhere.
- For TCP we should use SNI to derive destination service.

Generally speaking we do need to support multiple services for a single workload, both for source and destination, I think figuring that out should be high priority for 0.3.

**Comment by mandarjog** [comment]
A very pertinent use case for this is "breaking the monolith". You have a monolith that you want to decompose into multiple services. You start by defining logical services and updating client code to use those logical services.
The monolith is backing all those services. Gradually logical services move out to be their own micro services.

**Comment by kyessenov** [comment]
ref

**Comment by rshriram** [comment]
Based on whatever @smawson said, Envoy is already passing Host header. SNI support has been pushed to P1. So, I don't think we have anything else to do here, do we?

**Comment by costinm** [comment]
What's the relation to SNI ?

**Comment by smawson** [comment]
Note that host header and SNI are only useful for destination service, not source service. We need to handle both. The goal of SNI is to provide us the equivalent of the Host header, effectively.

One problem with Host header though is that in multi-hop scenarios it can be wrong, e.g. through Ingress it will give the external name instead of the local name. So we probably still need canonical service name or SNI to get the actual destination service.

And BTW actual destination service is needed, we're fine with canonical service for source, but not for destination, destination needs to be accurate since it drives policy etc.

Finally, SNI support may be a P1 but it is almost done and will end up in Envoy soon, so we should try to take advantage of it if the name is exposed.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1481](https://github.com/istio/istio/issues/1481) via [**ZenHub**](https://www.zenhub.com/)
