### ISSUE TITLE
Sidecar injection with mutating webhooks

### ISSUE THREAD

**Issue by andraxylia** [istio/old_pilot_repo#1474]

**Comment by ayj** [comment]
Initializers will not be beta in k8s 1.9. Instead the k8s API machinary SIG's plan is to push mutating webhooks to beta in 1.9. The automatic sidecar injection feature should use these mutating webhooks instead of the initializer mechanism.

Ref https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/OTApxKFiGt8

**Comment by linsun** [comment]
thank you @ayj !

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1464](https://github.com/istio/istio/issues/1464) via [**ZenHub**](https://www.zenhub.com/)
