### ISSUE TITLE
Diego BBS adapter for Pilot platform data

### ISSUE THREAD

**Issue by shalako** [istio/old_pilot_repo#1566]
Cloud Foundry Routing team is offering to submit a PR for an adapter and runtime options to use it.

Proposal: https://docs.google.com/document/d/16SexdTBgKyhM3ebUB4eVk-lJSXwiCDdJwH3L9yShf5o/edit?usp=sharing

@cmluciano

**Comment by cmluciano** [comment]
cc @istio/pilot-hackers

**Comment by shalako** [comment]
In Istio Slack #cloudfoundry, @kyessenov said:
> It seems to me in the same vein as consul/eureka/VM integration - it's fine for custom flags/deployment until we have a proper plugin model generalized in the config group. I would gladly accept contributions, but want to keep config group (@smawson and @louiscryan) in the loop for the architectural direction

Thank you!

**Comment by rshriram** [comment]
Do you have an ETA on when these platform adapters will be complete?

**Comment by shalako** [comment]
We plan to start next week. Don't have an ETA :)

**Comment by shalako** [comment]
We've begun implementation. Our progress can be tracked in https://www.pivotaltracker.com/story/show/151465998

**Comment by rshriram** [comment]
How do I comment on that thread?
Anyway I had a quick look at the code. It seems  to follow standard
patterns for consul and eureka, which is nice. It would be really nice if
you could have some form of integration test (with or without mocks).

I would also suggest starting the code contributions now rather than later,
so that we can have small PRs that allow for better review.

**Comment by nmahoney-pivotal** [comment]
@rshriram We've run into [a decision point that we are unsure about in pilot-discovery](https://github.com/istio/pilot/blob/master/cmd/pilot-discovery/main.go#L212-L226). We are trying to allow `pilot` to run without kubernetes, and we could use some guidance. We are planning on allowing users to pass in something like `--registries=cloudfoundry` and `--configStore=inMemory`. This would use Cloud Foundry as the platform and use the in-memory config store instead of kubernetes. Our main confusion is around what to do with the `admissionController`.

Options we are considering:
1. Only create the `admissionController` if the `configStore` is kubernetes AND kubernetes is a registered platform.
1. Only create the `admissionController` if the `configStore` is kubernetes OR kubernetes is a registered platform.
1. Only create the `admissionController` if the `configStore` is kubernetes.
1. Only create the `admissionController` if kubernetes is a registered platform.
1. Create the `admissionController` UNLESS the `configStore` is `inMemory` AND Cloud Foundry is the only registered platform.

These seemed like the most reasonable options, but we are open to other suggestions.

**Comment by andraxylia** [comment]
The automatic injection admissionController only makes sense if the platform is kubernetes. CF can work with manual injection (istioctl kube-inject)

The validation admissionController is used for config validation @ayj @costinm can the webhook validation happen outside of the k8s platform, like for instance in VMs, and is it included with the kube-api server?

**Comment by rshriram** [comment]
Stick to option 1. Along the way, please move this code into the switch
block. This code should never have been outside kubernetes. Sorry about the
trouble.

@ayj would you please move this logic under the kubernetes switch case? We
can’t run this in Consul or eureka in reliable fashion.

**Comment by ayj** [comment]
Option #3 looks good to me. The `admissionController` provides server-side configuration. It is a function of the `configStore` (e.g. k8s-apiserver) and not the service registry platform. 

I haven't validated [external admission webhooks](https://kubernetes.io/docs/admin/extensible-admission-controllers/#external-admission-webhooks) with standalone k8s-apiserver instructions for Consul/Eureka, but it should be workable in theory.

For CF you could either rely on client-side validation for proxy rules (via istioctl), or include server-side validation directly in the `inMemory` configStore implementation. See [AdmissionController.admit](https://github.com/istio/pilot/blob/4813d44d8146988c3ae6698f233eb2ff675ccc38/platform/kube/admit/admit.go#L356) as a reference for the latter case.

**Comment by nmahoney-pivotal** [comment]
@rshriram @ayj Thanks for the feedback! We've gone with option 1 for now. Let us know if we should change that decision.

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1371](https://github.com/istio/istio/issues/1371) via [**ZenHub**](https://www.zenhub.com/)
