### ISSUE TITLE
Auto figure out includeIPRanges by default

### ISSUE THREAD

**Issue by ldemailly** [istio/old_pilot_repo#903]
By default we should only intercept cluster traffic (or even istio managed services traffic)

We shouldn't need complex manual steps like
https://istio.io/docs/tasks/egress.html#calling-external-services-directly
for apps to continue to work with external services

A clean (k8s api driven) solution depends on https://github.com/kubernetes/kubernetes/issues/25533 but we should be able to figure out the value on our own (in istioctl or pilot from observing the registered services)

A brute force approach could be to get the list of managed ips through kubectl get svc and/or guess the netmask from said list

**Comment by cmluciano** [comment]
In upstream kube, it appears the goal is to read from a config-map for kube-proxy. This likely won't land in kube 1.8 since it is under development for kubelet.

**Comment by ldemailly** [comment]
interesting history and lots of good pointers and discussion in https://github.com/istio/pilot/issues/515

**Comment by ayj** [comment]
https://github.com/lyft/envoy/pull/1314 could also address this issue. @cmluciano, is this something you'd be willing to look into vs. waiting on upstream k8s to add the necessary information to a ConfigMap?

**Comment by rshriram** [comment]
i think @vadimeisenberg is working on this.  He already added the cluster
type but hasn't plugged it in fully.
-- 

~shriram

**Comment by ayj** [comment]
Great. Changing the milestone to 0.3 since a clean solution to auto-detected `includeIPRange` has an external dependency on https://github.com/kubernetes/kubernetes/issues/25533 which may not be ready for 0.2 release.

**Comment by ldemailly** [comment]
I'm not convinced we can ship 0.2 without some improvement in that area but let's see

**Comment by vadimeisenbergibm** [comment]
> By default we should only intercept cluster traffic (or even istio managed services traffic)

@ldemailly I think that in order to make the mesh more secure, Istio should control as much traffic as possible. One of the solutions that we are discussing with Egress design 0.2 is to allow external traffic to ports 443 only, for HTTPS, and all other external traffic to go thru sidecar proxies/dedicated egress proxies, controlled by egress rules and mixer security policies.

So I would not let all the external traffic go outside **by default**. I would even consider to remove --includeIPRanges option and to use --excludeIPRanges and --excludePorts instead. Suppose we have in v0.2 the following:

1. --excludeIPRanges and --excludePorts implemented (handles HTTPS and some corner cases)
2. all other traffic, e.g. to bluemix services will be defined by an egress rule with domain `*.bluemix.net` and this traffic will go thru a sidecar proxy (handles HTTP and TCP)

Will that solution be good enough for v0.2?

**Comment by ldemailly** [comment]
I don't think we should break existing applications no
I think both models have value

**Comment by vadimeisenbergibm** [comment]
But how will the existing applications be broken if we support --excludeIPRanges and --excludePorts and egress-rules with domains with wildcards ?

**Comment by kyessenov** [comment]
Issue moved to [istio/istio #1440](https://github.com/istio/istio/issues/1440) via [**ZenHub**](https://www.zenhub.com/)
